# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
#    env:
#      working-directory: ./back-end

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Stop Application
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          PID=`ps -ef | grep java | grep myblog-backend | grep Dspring.profiles.active=prod | awk '{print $2}'`
          echo $PID
          if [ -z "$PID" ]; then
            echo "> 실행중인 프로그램을 종료합니다."
            echo "> kill -9 $PID"
            kill -9 $PID
          else
            echo "> 실행중인 프로그램이 없습니다."
          fi

    - name: Deploy Remote Serve
      uses: appleboy/scp-action@v0.1.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "build/libs/*.jar"
        target: "myblog/back-end/"
        strip_components: 2

    - name: Run Application
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          if [ -f /home/airis/myblog/config/application-mysql.yml ]; then
            echo "> application-mysql파일이 존재합니다."
            echo "> Database: MySQL"
            echo "> nohup java -jar -Dspring.profiles.active=prod ${HOME}/myblog/back-end/*.jar"
            nohup java -jar -Dspring.profiles.active=prod ${HOME}/myblog/back-end/*.jar >> nohup.out 2>&1 &
          # else
          #   echo "> application-mysql파일이 없습니다."
          #   echo "> Database: H2"
          #   echo "> nohup java -jar /home/airis/myblog/sample-board-0.0.1-SNAPSHOT.jar"
          #   nohup java -jar /home/airis/myblog/sample-board-0.0.1-SNAPSHOT.jar &
          fi	
          sleep 1
          echo "> 실행을 완료 했습니다."